### ISSUE TITLE
Old entries are still displayed

### ISSUE THREAD

**Issue by p00f** [Biont/sway-launcher-desktop#46]
Desktop entries from uninstalled programs are still displayed in the list, even after running `sudo update-desktop-databse` and deleting the launcher history file

For example, I get an entry for Covergrid here even after uninstalling it
![image](https://user-images.githubusercontent.com/36493671/123134954-ed708f00-d46e-11eb-8c34-ffd308f2b7ad.png)
On the top you can see that `sed` can't find the desktop file, which probably comes from here
https://github.com/Biont/sway-launcher-desktop/blob/74ed255995f5935804235daf731471a422d44075/sway-launcher-desktop.sh#L68

Can I clear it somehow?

**Comment by p00f** [comment]
@Biont where are the desktop entries taken from?

**Comment by Biont** [comment]
I find it very strange that this happens after deleting the history file - because that's the only place where stale entries would be coming from. Are you using multiple providers and maybe missed one @p00f ?

The entries are read using [this configuration](https://github.com/Biont/sway-launcher-desktop/blob/master/sway-launcher-desktop.sh#L95): `${XDG_DATA_HOME-${HOME}/.local/share}:${XDG_DATA_DIRS-/usr/local/share:/usr/share}`
There's no cache or anything at play here.

**Comment by p00f** [comment]
I add `HIST_FILE="~/.local/state/swaylauncher_history" ` as an argument (because latest XDG spec says logs and history go to `$XDG_STATE_HOME` which is `~/.local/state`). When I removed that argument and let it save in `~/.cache`, the stale entries are gone.

**Comment by maricn** [comment]
fixed by https://github.com/Biont/sway-launcher-desktop/pull/58 - you can `sway-launcher-desktop purge` since v1.6.0

**Comment by Biont** [comment]
Thanks @maricn 

I tracked the useful remark about `XDG_STATE_HOME` in #65 so we can close here
